name: Run RSpec

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_rspec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install libvips
        run: sudo apt-get install --fix-missing -qq -o Acquire::Retries=3 libvips

      - name: Install Bundler
        run: gem install bundler -v '~>2.4.22'

      - name: Install Dependencies
        run: bundle install

      - name: Run RSpec
        run: bundle exec rspec
